"""add task_uuid column

Revision ID: 510febb52ba6
Revises: ed14438701a2
Create Date: 2026-07-12 18:58:08.627629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510febb52ba6'
down_revision: Union[str, None] = 'ed14438701a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_tasks', sa.Column('task_uuid', sa.String(length=100), nullable=False, comment='任务唯一标识'))
    op.drop_index('ix_training_tasks_task_uid', table_name='training_tasks')
    op.create_index(op.f('ix_training_tasks_task_uuid'), 'training_tasks', ['task_uuid'], unique=True)
    op.drop_column('training_tasks', 'task_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_tasks', sa.Column('task_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='任务唯一标识'))
    op.drop_index(op.f('ix_training_tasks_task_uuid'), table_name='training_tasks')
    op.create_index('ix_training_tasks_task_uid', 'training_tasks', ['task_uid'], unique=False)
    op.drop_column('training_tasks', 'task_uuid')
    # ### end Alembic commands ###
