"""Add reset_verification_code fields

Revision ID: 5a33e7412608
Revises: 1904be0a99ce
Create Date: 2026-07-20 15:44:55.136364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a33e7412608'
down_revision: Union[str, Sequence[str], None] = '1904be0a99ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='消息角色: user/assistant/tool/system',
               existing_comment='消息角色：user/assistant/tool/system',
               existing_nullable=False)
    op.alter_column('chat_messages', 'agent_used',
               existing_type=sa.VARCHAR(length=50),
               comment='处理的Agent: supervisor/detection/analysis/qa',
               existing_comment='处理的 Agent：supervisor/detection/analysis/qa',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tool_calls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='工具调用记录',
               existing_comment='工具调用记录，如 [{"tool":"detect_objects","args":{...}}]',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment='Token消耗量',
               existing_comment='Token 消耗量',
               existing_nullable=True)
    op.alter_column('chat_messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='响应耗时(毫秒)',
               existing_comment='响应耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='会话标题',
               existing_comment='会话标题（取第一条消息摘要）',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: active/archived',
               existing_comment='状态：active/archived',
               existing_nullable=True)
    op.alter_column('detection_results', 'class_id',
               existing_type=sa.INTEGER(),
               comment='类别ID',
               existing_comment='类别 ID',
               existing_nullable=False)
    op.alter_column('detection_results', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='置信度0-1',
               existing_comment='置信度 0~1',
               existing_nullable=False)
    op.alter_column('detection_results', 'bbox',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='边界框[x1,y1,x2,y2]',
               existing_comment='边界框 [x1, y1, x2, y2]',
               existing_nullable=False)
    op.alter_column('detection_results', 'inference_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='该图推理耗时(ms)',
               existing_comment='该图推理耗时（ms）',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景标识,如 remote_sensing',
               existing_comment='场景标识，如 remote_sensing',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景显示名,如遥感目标检测',
               existing_comment='场景显示名，如 遥感目标检测',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='场景分类: agriculture/industry/remote_sensing/medical/traffic',
               existing_comment='场景分类：agriculture/industry/remote_sensing/medical/traffic',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'class_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别列表,如 ["airplane","storage-tank"]',
               existing_comment='类别列表，如 ["airplane","storage-tank"]',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'class_names_cn',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别中文名映射,如 {"airplane":"飞机"}',
               existing_comment='类别中文名映射，如 {"airplane":"飞机"}',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               comment='检测类型: single/batch/folder/video/camera',
               existing_comment='检测类型：single/batch/folder/video/camera',
               existing_nullable=False)
    op.alter_column('detection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: pending/processing/completed/failed',
               existing_comment='状态：pending/processing/completed/failed',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'total_inference_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总推理耗时(ms)',
               existing_comment='总推理耗时（ms）',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'analysis_report',
               existing_type=sa.TEXT(),
               comment='分析报告(Markdown格式)',
               existing_comment='分析报告（Markdown 格式）',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='风险等级: low/medium/high/critical',
               existing_comment='风险等级：low/medium/high/critical',
               existing_nullable=True)
    op.alter_column('model_versions', 'training_task_id',
               existing_type=sa.INTEGER(),
               comment='来源训练任务',
               existing_comment='来源训练任务（可为空，支持手动上传）',
               existing_nullable=True)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='版本号，如v1.0.0',
               existing_comment='版本号，如 v1.0.0',
               existing_nullable=False)
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               comment='模型类型: yolov11n/s/m/l/x',
               existing_comment='模型类型：yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: active/archived/deleted',
               existing_comment='状态：active/archived/deleted',
               existing_nullable=True)
    op.alter_column('model_versions', 'minio_url',
               existing_type=sa.VARCHAR(length=500),
               comment='MinIO存储URL',
               existing_comment='MinIO 存储 URL',
               existing_nullable=True)
    op.alter_column('model_versions', 'per_class_ap',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='各类别AP',
               existing_comment='各类别 AP，如 {"airplane":0.85,"tank":0.72}',
               existing_nullable=True)
    op.alter_column('operation_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='操作用户',
               existing_comment='操作用户（可为空表示系统操作）',
               existing_nullable=True)
    op.alter_column('operation_logs', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='冗余用户名',
               existing_comment='冗余用户名，方便查询',
               existing_nullable=True)
    op.alter_column('operation_logs', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='操作模块: auth/detection/training/agent/system',
               existing_comment='操作模块：auth/detection/training/agent/system',
               existing_nullable=False)
    op.alter_column('operation_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型: create/update/delete/login/export',
               existing_comment='操作类型：create/update/delete/login/export',
               existing_nullable=False)
    op.alter_column('operation_logs', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作对象类型: user/task/model/session',
               existing_comment='操作对象类型：user/task/model/session',
               existing_nullable=True)
    op.alter_column('operation_logs', 'target_id',
               existing_type=sa.VARCHAR(length=100),
               comment='操作对象ID',
               existing_comment='操作对象 ID',
               existing_nullable=True)
    op.alter_column('operation_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment='客户端IP',
               existing_comment='客户端 IP',
               existing_nullable=True)
    op.alter_column('operation_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='客户端User-Agent',
               existing_comment='客户端 User-Agent',
               existing_nullable=True)
    op.alter_column('operation_logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP方法',
               existing_comment='HTTP 方法',
               existing_nullable=True)
    op.alter_column('operation_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='操作结果: success/failure',
               existing_comment='操作结果：success/failure',
               existing_nullable=True)
    op.alter_column('operation_logs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_comment='失败时的错误信息',
               existing_nullable=True)
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限编码,如detection:task:create',
               existing_comment='权限编码，如 detection:task:create',
               existing_nullable=False)
    op.alter_column('permissions', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='所属模块: auth/detection/training/agent/system',
               existing_comment='所属模块：auth/detection/training/agent/system',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色标识,如admin/operator/viewer',
               existing_comment='角色标识，如 admin/operator/viewer',
               existing_nullable=False)
    op.alter_column('roles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='角色显示名,如管理员/操作员/访客',
               existing_comment='角色显示名，如 管理员/操作员/访客',
               existing_nullable=False)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否系统内置角色(不可删除)',
               existing_comment='是否系统内置角色（不可删除）',
               existing_nullable=True)
    op.alter_column('training_metrics', 'dfl_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='DFL损失',
               existing_comment='DFL 损失',
               existing_nullable=True)
    op.alter_column('training_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态: pending/running/completed/failed/cancelled',
               existing_comment='状态：pending/running/completed/failed/cancelled',
               existing_nullable=True)
    op.alter_column('training_tasks', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='基础模型: yolov11n/s/m/l/x',
               existing_comment='基础模型：yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('training_tasks', 'device',
               existing_type=sa.VARCHAR(length=20),
               comment='训练设备: 0/1/cpu',
               existing_comment='训练设备：0/1/cpu',
               existing_nullable=True)
    op.alter_column('training_tasks', 'optimizer',
               existing_type=sa.VARCHAR(length=20),
               comment='优化器: SGD/Adam/AdamW',
               existing_comment='优化器：SGD/Adam/AdamW',
               existing_nullable=True)
    op.alter_column('training_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='进度百分比 0-100',
               existing_comment='进度百分比 0~100',
               existing_nullable=True)
    op.add_column('users', sa.Column('reset_verification_code', sa.String(length=10), nullable=True, comment='密码重置验证码(6位数字)'))
    op.add_column('users', sa.Column('reset_verification_code_expires_at', sa.DateTime(), nullable=True, comment='验证码过期时间'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='邮箱是否已验证',
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='邮箱是否已验证',
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'reset_verification_code_expires_at')
    op.drop_column('users', 'reset_verification_code')
    op.alter_column('training_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='进度百分比 0~100',
               existing_comment='进度百分比 0-100',
               existing_nullable=True)
    op.alter_column('training_tasks', 'optimizer',
               existing_type=sa.VARCHAR(length=20),
               comment='优化器：SGD/Adam/AdamW',
               existing_comment='优化器: SGD/Adam/AdamW',
               existing_nullable=True)
    op.alter_column('training_tasks', 'device',
               existing_type=sa.VARCHAR(length=20),
               comment='训练设备：0/1/cpu',
               existing_comment='训练设备: 0/1/cpu',
               existing_nullable=True)
    op.alter_column('training_tasks', 'model_name',
               existing_type=sa.VARCHAR(length=50),
               comment='基础模型：yolov11n/s/m/l/x',
               existing_comment='基础模型: yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('training_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：pending/running/completed/failed/cancelled',
               existing_comment='状态: pending/running/completed/failed/cancelled',
               existing_nullable=True)
    op.alter_column('training_metrics', 'dfl_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='DFL 损失',
               existing_comment='DFL损失',
               existing_nullable=True)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='是否系统内置角色（不可删除）',
               existing_comment='是否系统内置角色(不可删除)',
               existing_nullable=True)
    op.alter_column('roles', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='角色显示名，如 管理员/操作员/访客',
               existing_comment='角色显示名,如管理员/操作员/访客',
               existing_nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='角色标识，如 admin/operator/viewer',
               existing_comment='角色标识,如admin/operator/viewer',
               existing_nullable=False)
    op.alter_column('permissions', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='所属模块：auth/detection/training/agent/system',
               existing_comment='所属模块: auth/detection/training/agent/system',
               existing_nullable=False)
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限编码，如 detection:task:create',
               existing_comment='权限编码,如detection:task:create',
               existing_nullable=False)
    op.alter_column('operation_logs', 'error_message',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_comment='失败时的错误信息',
               existing_nullable=True)
    op.alter_column('operation_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='操作结果：success/failure',
               existing_comment='操作结果: success/failure',
               existing_nullable=True)
    op.alter_column('operation_logs', 'request_method',
               existing_type=sa.VARCHAR(length=10),
               comment='HTTP 方法',
               existing_comment='HTTP方法',
               existing_nullable=True)
    op.alter_column('operation_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='客户端 User-Agent',
               existing_comment='客户端User-Agent',
               existing_nullable=True)
    op.alter_column('operation_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=50),
               comment='客户端 IP',
               existing_comment='客户端IP',
               existing_nullable=True)
    op.alter_column('operation_logs', 'target_id',
               existing_type=sa.VARCHAR(length=100),
               comment='操作对象 ID',
               existing_comment='操作对象ID',
               existing_nullable=True)
    op.alter_column('operation_logs', 'target_type',
               existing_type=sa.VARCHAR(length=50),
               comment='操作对象类型：user/task/model/session',
               existing_comment='操作对象类型: user/task/model/session',
               existing_nullable=True)
    op.alter_column('operation_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               comment='操作类型：create/update/delete/login/export',
               existing_comment='操作类型: create/update/delete/login/export',
               existing_nullable=False)
    op.alter_column('operation_logs', 'module',
               existing_type=sa.VARCHAR(length=50),
               comment='操作模块：auth/detection/training/agent/system',
               existing_comment='操作模块: auth/detection/training/agent/system',
               existing_nullable=False)
    op.alter_column('operation_logs', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='冗余用户名，方便查询',
               existing_comment='冗余用户名',
               existing_nullable=True)
    op.alter_column('operation_logs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='操作用户（可为空表示系统操作）',
               existing_comment='操作用户',
               existing_nullable=True)
    op.alter_column('model_versions', 'per_class_ap',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='各类别 AP，如 {"airplane":0.85,"tank":0.72}',
               existing_comment='各类别AP',
               existing_nullable=True)
    op.alter_column('model_versions', 'minio_url',
               existing_type=sa.VARCHAR(length=500),
               comment='MinIO 存储 URL',
               existing_comment='MinIO存储URL',
               existing_nullable=True)
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：active/archived/deleted',
               existing_comment='状态: active/archived/deleted',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_type',
               existing_type=sa.VARCHAR(length=50),
               comment='模型类型：yolov11n/s/m/l/x',
               existing_comment='模型类型: yolov11n/s/m/l/x',
               existing_nullable=True)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='版本号，如 v1.0.0',
               existing_comment='版本号，如v1.0.0',
               existing_nullable=False)
    op.alter_column('model_versions', 'training_task_id',
               existing_type=sa.INTEGER(),
               comment='来源训练任务（可为空，支持手动上传）',
               existing_comment='来源训练任务',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               comment='风险等级：low/medium/high/critical',
               existing_comment='风险等级: low/medium/high/critical',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'analysis_report',
               existing_type=sa.TEXT(),
               comment='分析报告（Markdown 格式）',
               existing_comment='分析报告(Markdown格式)',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'total_inference_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总推理耗时（ms）',
               existing_comment='总推理耗时(ms)',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：pending/processing/completed/failed',
               existing_comment='状态: pending/processing/completed/failed',
               existing_nullable=True)
    op.alter_column('detection_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               comment='检测类型：single/batch/folder/video/camera',
               existing_comment='检测类型: single/batch/folder/video/camera',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'class_names_cn',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别中文名映射，如 {"airplane":"飞机"}',
               existing_comment='类别中文名映射,如 {"airplane":"飞机"}',
               existing_nullable=True)
    op.alter_column('detection_scenes', 'class_names',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='类别列表，如 ["airplane","storage-tank"]',
               existing_comment='类别列表,如 ["airplane","storage-tank"]',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='场景分类：agriculture/industry/remote_sensing/medical/traffic',
               existing_comment='场景分类: agriculture/industry/remote_sensing/medical/traffic',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'display_name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景显示名，如 遥感目标检测',
               existing_comment='场景显示名,如遥感目标检测',
               existing_nullable=False)
    op.alter_column('detection_scenes', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='场景标识，如 remote_sensing',
               existing_comment='场景标识,如 remote_sensing',
               existing_nullable=False)
    op.alter_column('detection_results', 'inference_time',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='该图推理耗时（ms）',
               existing_comment='该图推理耗时(ms)',
               existing_nullable=True)
    op.alter_column('detection_results', 'bbox',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='边界框 [x1, y1, x2, y2]',
               existing_comment='边界框[x1,y1,x2,y2]',
               existing_nullable=False)
    op.alter_column('detection_results', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='置信度 0~1',
               existing_comment='置信度0-1',
               existing_nullable=False)
    op.alter_column('detection_results', 'class_id',
               existing_type=sa.INTEGER(),
               comment='类别 ID',
               existing_comment='类别ID',
               existing_nullable=False)
    op.alter_column('chat_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态：active/archived',
               existing_comment='状态: active/archived',
               existing_nullable=True)
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='会话标题（取第一条消息摘要）',
               existing_comment='会话标题',
               existing_nullable=True)
    op.alter_column('chat_messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='响应耗时（毫秒）',
               existing_comment='响应耗时(毫秒)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tokens_used',
               existing_type=sa.INTEGER(),
               comment='Token 消耗量',
               existing_comment='Token消耗量',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tool_calls',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='工具调用记录，如 [{"tool":"detect_objects","args":{...}}]',
               existing_comment='工具调用记录',
               existing_nullable=True)
    op.alter_column('chat_messages', 'agent_used',
               existing_type=sa.VARCHAR(length=50),
               comment='处理的 Agent：supervisor/detection/analysis/qa',
               existing_comment='处理的Agent: supervisor/detection/analysis/qa',
               existing_nullable=True)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='消息角色：user/assistant/tool/system',
               existing_comment='消息角色: user/assistant/tool/system',
               existing_nullable=False)
    # ### end Alembic commands ###
