"""add_geo_fields_to_detection_tasks_and_results

Revision ID: 7cb1307f7329
Revises: 1904be0a99ce
Create Date: 2026-07-23 16:02:00.820977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb1307f7329'
down_revision: Union[str, Sequence[str], None] = '1904be0a99ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_results', sa.Column('latitude', sa.Float(), nullable=True, comment='检测位置纬度'))
    op.add_column('detection_results', sa.Column('longitude', sa.Float(), nullable=True, comment='检测位置经度'))
    op.add_column('detection_tasks', sa.Column('latitude', sa.Float(), nullable=True, comment='检测位置纬度'))
    op.add_column('detection_tasks', sa.Column('longitude', sa.Float(), nullable=True, comment='检测位置经度'))
    op.add_column('detection_tasks', sa.Column('location_name', sa.String(length=200), nullable=True, comment='位置描述，如XX农场3号田'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_tasks', 'location_name')
    op.drop_column('detection_tasks', 'longitude')
    op.drop_column('detection_tasks', 'latitude')
    op.drop_column('detection_results', 'longitude')
    op.drop_column('detection_results', 'latitude')
    # ### end Alembic commands ###
