"""add_knowledge_tables

Revision ID: f1466777177b
Revises: ed14438701a2
Create Date: 2026-07-14 16:07:28.029630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f1466777177b'
down_revision: Union[str, Sequence[str], None] = 'ed14438701a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 确保 pgvector 扩展可用
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型：pdf/txt/md'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='原始文件路径'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='切片数量'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='来源类型：upload（用户上传）/ preset（系统预置）'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='上传人'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='所属文档'),
    sa.Column('content', sa.Text(), nullable=False, comment='片段文本内容'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='片段元数据（页码、章节等）'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='文本向量（text-embedding-v3）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
